### ISSUE TITLE
What is the meaning for the data in test1 and Eval1 floder

### ISSUE THREAD

**Issue by echozheng** [rmgitting/autoCEP#1]
Hi, @rmgitting, it is so nice that you share your project with us.
After reading the paper, I download your code from the github.
But I am still confused with the test data and the eval data.
Could you please give me some details about that, thank you.

**Comment by rmgitting** [comment]
Hello @echozheng, I was a little away this weekend so I just noticed your comment, and therefore I am sincerely sorry for the delay.
Regarding the folders, there was an error in the name, the test data should be the training data, I misspelled the name of the folder, and I just fixed it now. 
Please excuse me for the confusion I caused.

The train1 folder now contains training data that could be used to learn shapelets if you want to try the learning. The Eval1 folder contains other data for evaluation, these data are without classification inside the csv files, but you can tell the true class from the name of the file, and compare it with the result autoCEP will yield.
In order to spare you the learning time, an sql file exists in the git folder, you can charge it into your MySQL server (if you have any), and then load the shapelets as demonstrated in the video.
I hope I answered your question.

I remain completely at your disposal should you have further questions.

**Comment by echozheng** [comment]
@rmgitting, thank you so muck for your response, it means a lot to me.
I read your code (ShapeletTrainer and CEPRuleExtraction)carefully these days. It is remarkable that you use java 8 function-style programming.
I still have some questions about the train data and the code, as following:

1、in the paper _Demo:Complex Event Processing for the Non-Expert with autoCEP_, you mention the data were generated during the artworks transportation by specific temperature sensors. And here comes my doubt - what kind of those transportation? What are the connection between "Stairs", "Walk","Computer" and the data?
As Example: (from train1/Computer87.csv)
**"791","1880.0","1"
"792","1878.3333333333333","1"
"793","1876.6666666666667","1"
"794","1879.3333333333333","1"
"795","1877.3333333333333","1"
"796","1880.0","1"
"797","1875.6666666666667","1"
"798","1877.3333333333333","1"
"799","1878.3333333333333","1"
"12","Computer","12"**
could you please tell me the meaning of those data(can the temperature be high than 1800 degrees centigrade)?

2、function entropyHelper()， in the class of Shapelet.
     _**private double entropyHelper(double c1, double c2) {
        return (c2 != 0 ?
		-1.0 * Global.entropy(c1, c1 + c2) - 1.0 * Global.entropy(c2, c1 + c2) - 1.0 * Global.entropy(c1, c1 + c2) - 1.0 * Global.entropy(c2, c1 + c2)
                : -1.0 * Global.entropy(c1, c1 + c2));
    }**_
I know the purpose of this function is to calculate the information gain for the shapelet, but it seems different with the formula： I(D)=-p(A)log(p(A)) - p(B)log(p(B)).

3、How a shapelet turns into a CEP rule? What is the size for the window and what will be the condition block? I don't find any transformation in your code.

Thanks for your time and wish you have a good day.

**Comment by rmgitting** [comment]
Hello again @echozheng, you are welcome anytime.
Regarding your first question, the training and the evaluation data that I provided in the git repository are not for artwork transportation processes. Unfortunately, the logs from the transportation processes are confidential and our partner don't accept to provide them for public access. The data you find here are some activity recognition data, that is to recognize human activities. I included these data so users can test and toy with autoCEP since I can't include the transportation processes. Basically, they are accelerometer data.

Regarding the information gain, I used a formula that is discusses in this paper: Early Classification of multivariate temporal observations by extraction of interpretable shapelets. You may find useful information about it. And the helper methods in my java code help me to achieve this formula.

Lastly, the window is the size of the shapelets, and the condition is the Euclidean distance. However, it is all done in a single CEP rule (because of some technical issues I had to scale in Esper) and the engine then perform the windowing and test the conditions through listeners.

Frankly, I stopped working on this version of autoCEP, and now I have a more advanced and a functional version that works with multivariate time series, and create many complex CEP rules. If you want, and in case you have some instant chat (IM) accounts like a slack account, you can give it to me and then we can discuss. Get to know you better, and know what you are working at, and I  can show you my latest advancements in this field.

Regards,

**Comment by echozheng** [comment]
hello again, @rmgitting.
That's cool, I look forward to communicating with you.
Here in China, we use WeChat, QQ a lot.
I register a slack account this morning, while i still don't familiar with it.
mail: 1991echosilly@gmail.com
